### ISSUE TITLE
BAD_REQUEST - "limit" must be less than or equal to 20

### ISSUE THREAD

**Issue by cwagner22** [crabada-resources/looting_statistics#1]
Crabada has added a limit to the api endpoints, now the limit is 20 results per page, except for the lending which seems to be 50.

@dinizime

**Comment by Drotak** [comment]
Hello @cwagner22,

I have opened a pull request which resolves this issue.

**Comment by cwagner22** [comment]
@Drotak You rock :)

**Comment by jlebutte** [comment]
I tried after the PR but I got another error :(

![image](https://user-images.githubusercontent.com/2816633/154257333-2e47266c-0cc6-401e-aa59-06483393d44e.png)

**Comment by Drotak** [comment]
Yes, I also got this issue yesterday, but this is a problem with the crabada API and not with this tool.. For me time solved the issue ;)

**Comment by fenicks** [comment]
By checking the result data this issue is solved.
Could you check? Cc @cwagner22 @jlebutte.

**Comment by jlebutte** [comment]
Yes, it seems solved. I have missing data (mining before Jan 31) but I guess it's an issue with the API itself
